Simple CRUD, Bean Validation and Exception Handling
event-sphere-org/user-service pull request #1
Opened 2023-05-23 09:02 UTC by nbugaenco

This pull request introduces several enhancements to the User Service microservice. The changes focus on implementing a simple CRUD (Create, Read, Update, Delete) functionality for managing user accounts, while incorporating bean validation and exception handling.

1. **Controller**: The `UserController` class is updated to include the necessary REST endpoints for user management. These endpoints enable the retrieval of all users, fetching a specific user by ID, creating a new user, updating user information, changing passwords, and deleting users. The endpoints are properly annotated with `@GetMapping`, `@PostMapping`, `@PutMapping`, `@PatchMapping`, and `@DeleteMapping` annotations, along with path variables and request bodies as required.

2. **Service**: The `UserService` class is introduced to handle the business logic for user operations. It includes methods for retrieving all users, fetching a user by ID, creating a new user, updating user information, changing passwords, and deleting users. The service utilizes the `UserRepository` to interact with the underlying database.

3. **Exceptions**: Custom exception classes are created to handle specific error scenarios. These exceptions include `UserNotFoundException`, `UserNotValidException`, `PasswordException`, and `UserAlreadyExistsException`. Each exception extends the `RuntimeException` class and is appropriately annotated with `@ResponseStatus` to indicate the corresponding HTTP status codes.

4. **Exception Handling**: A global exception handler is implemented using the `UserServiceResponseEntityExceptionHandler` class. It extends `ResponseEntityExceptionHandler` and provides methods to handle various exceptions thrown within the application. These exception handlers generate appropriate error responses with relevant details, including timestamp, error message, and error details.

5. **DTOs**: Several DTO (Data Transfer Object) classes are introduced to facilitate data exchange between the client and the server. These DTOs include `UserDto` for updating user information and `ChangePasswordDto` for changing passwords. They include validation annotations, such as `@Size` and `@Pattern`, to enforce data integrity.

6. **Utilities**: The `ErrorUtils` class is created to provide a utility method for converting field errors into a map of field names and error messages. This utility is used in the exception handling process to generate more structured error responses.

2023-05-26 19:41 UTC, vicol13 commented
1. Where are unit tests ?

2023-05-26 19:45 UTC, nbugaenco commented
I forgor 💀
Will be done Morning.

2023-05-26 19:53 UTC, vicol13 requested changes

2023-05-26 19:53 UTC, vicol13 commented on src/main/java/com/eventsphere/user/service/UserService.java
> +    }
You have across this class useless declaration of user you can do instead something like this : 
``` java 
 public User create(User user) {


        if (userRepository.existsByUsername(user.getUsername())) {
            throw new UserAlreadyExistsException("This username is already registered");
        } else if (userRepository.existsByEmail(user.getEmail())) {
            throw new UserAlreadyExistsException("This email is already registered");
        } 
            
           return save(user);
    }
```

2023-05-26 19:53 UTC, vicol13 commented on src/main/java/com/eventsphere/user/service/UserService.java
> +            ex.printStackTrace();
isn't this function printing stack to ``System.out`` ?

2023-05-26 19:53 UTC, vicol13 commented on src/main/java/com/eventsphere/user/service/UserService.java
> +    public User update(Long userId, UserDto userDto) {
Please rethink this bit of logic because it will require to add a new if every time if we want to add a new field to the user

2023-05-31 17:26 UTC, vicol13 commented on src/test/java/com/eventsphere/user/controller/UserControllerTest.java
> +        when(userService.getAll()).thenReturn(users);
```java
thenReturn(List.of(....)) 
```

2023-05-31 17:27 UTC, vicol13 approved these changes

2023-06-01 15:12 UTC, merged